version: '3.8'
services:
  nifi:
    image: apache/nifi:1.23.2
    container_name: nifi-day02
    ports:
      - "8080:8080"
    environment:
      - NIFI_WEB_HTTP_PORT=8080
    volumes:
      - ../lab-02/inputs:/opt/nifi/inputs
      - ../lab-02/outputs:/opt/nifi/outputs
      - ../lab-02/quarantine:/opt/nifi/quarantine
    restart: unless-stopped
